version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: todoist
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    ports:
      - 5003:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 5004:8080
  
  backend:
    build: ./backend
    restart: always
    ports:
      - 5000:8080
    volumes:
      - ./backend/src:/usr/src/app/src
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://root:root@db:5432/todoist
